version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    image: jrtec/fastapi-alembic-sqlmodel-async:main
    restart: always
    command: "sh -c 'alembic upgrade head && python app/initial_data.py && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./fastapi-alembic-sqlmodel-async:/code
    expose:
      - 8000
    env_file: ".env"
    depends_on:
      - postgres
    links:
      - traefik-proxy:storage.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi_local.entrypoints=web"
      - "traefik.http.routers.fastapi_local.rule=Host(`fastapi.${LOCAL_1}`, `fastapi.${LOCAL_2}`, `fastapi.${EXT_ENDPOINT1}`)"
      - "traefik.http.routers.fastapi_local_base.entrypoints=web"
      - "traefik.http.routers.fastapi_local_base.rule=Host(`${LOCAL_1}`, `${LOCAL_2}`, `${EXT_ENDPOINT1}`)"
      - traefik.http.services.fastapi_localservice.loadbalancer.server.port=8000

  postgres:
    image: bitnami/postgresql:13.3.0
    restart: always
    container_name: postgres
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/bitnami/postgresql
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    env_file: ".env"
    volumes:
      - ./mariadb/data:/var/lib/mysql/data
      - ./mariadb/logs:/var/lib/mysql/logs
    expose:
      - 3306
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    # ports:
    #   - 8090:80
    expose:
      - 8090
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin_local.entrypoints=web"
      - "traefik.http.routers.phpmyadmin_local.rule=Host(`phpmyadmin.${LOCAL_1}`, `phpmyadmin.${LOCAL_2}`, `phpmyadmin.${EXT_ENDPOINT1}`)"
      # - traefik.http.services.phpmyadmin_local_service.loadbalancer.server.port=8090

  # php_fpm 7.4, 8.0, 8.1, 8.2 etc
  # node_server
  #   svelte, sveltekit, learn.svelte, nestjs etc

  redis_server:
    container_name: redis_server
    image: "redis:alpine"
    restart: always
    expose:
      - 6379
    env_file: .env

  nginx_server:
    container_name: nginx_server
    restart: unless-stopped
    logging:
      driver: none
    image: "nginx:latest"
    expose:
      - 8080
    volumes:
      - ./static:/code/static
      - ./nginx-config-files/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config-files/app.nginx.template:/etc/nginx/templates/app.nginx.template
      - "${EB_LOG_BASE_DIR:-./nginx-config-files}/nginx-proxy:/var/log/nginx"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_local.entrypoints=web"
      - "traefik.http.routers.nginx_local.rule=Host(`nginx.${LOCAL_1}`, `nginx.${LOCAL_2}`, `nginx.${EXT_ENDPOINT1}`)"
      - traefik.http.services.nginx_local_service.loadbalancer.server.port=8080

  minio_server:
    image: minio/minio:latest
    restart: always
    container_name: minio_server
    volumes:
      - ./minio/data:/data
    expose:
      - 9000
      - 9091
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: http://stash.localhost
    command: "server /data --console-address ':9090'"
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.routers.minio.service=minio
      - traefik.http.routers.minio.rule=Host(`storage.${LOCAL_1}`, `storage.${LOCAL_2}`, `storage.${EXT_ENDPOINT1}`)
      - traefik.http.services.minio.loadbalancer.server.port=9000
      - traefik.http.routers.minio-console.entrypoints=web
      - traefik.http.routers.minio-console.service=minio-console
      - traefik.http.routers.minio-console.rule=Host(`stash.${LOCAL_1}`, `stash.${LOCAL_2}`, `stash.${EXT_ENDPOINT1}`)
      - traefik.http.services.minio-console.loadbalancer.server.port=9090

  traefik-proxy:
    container_name: traefik-proxy
    restart: always
    image: "traefik:latest"
    command:
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik.yml:/traefik.yml:ro
      - "./traefik/letsencrypt:/home/letsencrypt"
      - ./traefik/.htpasswd:/.htpasswd
      - "${EB_LOG_BASE_DIR:-./traefik}/traefik-proxy:/logs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${LOCAL_1}`, `traefik.${LOCAL_2}`, `traefik.${EXT_ENDPOINT1}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/.htpasswd"
  sveltekit:
    container_name: sveltekit
    restart: always
    build:
      context: ./svelte/kit
      dockerfile: Dockerfile
    # command: "sh -c 'npm install && npm run dev'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelte_local.entrypoints=web"
      - "traefik.http.routers.svelte_local.rule=Host(`sveltekit.${LOCAL_1}`, `sveltekit.${LOCAL_2}`, `sveltekit.${EXT_ENDPOINT1}`)"
      - "traefik.http.routers.node-server.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
