api:
  dashboard: true
  # insecure: true # Don't do that in production

# Entrypoints
entryPoints:
  web:
    address: :80

  websecure:
    address: :443

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  filePath: "/traefik/logs/traefik.log"
  format: json
  level: DEBUG

accessLog:
  filePath: "/traefik/logs/access.log"

# certificatesResolvers:
#   http:
#     acme:
#       email: name@gmail.com
#       storage: acme.json
#       httpChallenge:
#         entryPoint: http

# serversTransport:
#   insecureSkipVerify: true